"""Tests for PDF extraction and file hashing."""

import hashlib
import re
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from academic_paper.extractor import extract_text, hash_file


def test_hash_file(tmp_path: Path) -> None:
    test_file = tmp_path / "test.txt"
    test_content = b"Hello, World! This is test content."
    test_file.write_bytes(test_content)

    hash1 = hash_file(str(test_file))
    assert isinstance(hash1, str)
    assert len(hash1) == 64
    assert all(c in "0123456789abcdef" for c in hash1)
    assert hash1 == hash_file(str(test_file))
    assert hash1 == hashlib.sha256(test_content).hexdigest()

    test_file2 = tmp_path / "test2.txt"
    test_file2.write_bytes(b"Different content")
    assert hash_file(str(test_file2)) != hash1


def _make_word(text: str, x0: float = 0.0) -> dict:
    return {"text": text, "x0": x0, "x1": x0 + 10, "top": 0, "bottom": 10}


def test_extract_text_empty_pages_skipped() -> None:
    mock_pdf = MagicMock()
    mock_page1 = MagicMock()
    mock_page1.extract_words.return_value = [_make_word("Page"), _make_word("one")]
    mock_page2 = MagicMock()
    mock_page2.extract_words.return_value = []  # empty
    mock_page3 = MagicMock()
    mock_page3.extract_words.return_value = [_make_word("Page"), _make_word("three")]
    mock_pdf.pages = [mock_page1, mock_page2, mock_page3]

    with patch("pdfplumber.open") as mock_open:
        mock_open.return_value.__enter__.return_value = mock_pdf
        result = extract_text("/fake/path.pdf")

    assert len(result) == 2
    assert result[0]["page"] == 1
    assert result[0]["text"] == "Page one"
    assert result[1]["page"] == 3
    assert result[1]["text"] == "Page three"


def test_extract_text_words_joined_with_spaces() -> None:
    """extract_words() output must be joined with spaces — no merged tokens."""
    mock_pdf = MagicMock()
    mock_page = MagicMock()
    mock_page.extract_words.return_value = [
        _make_word("KV"),
        _make_word("cache"),
        _make_word("reduces"),
        _make_word("latency"),
    ]
    mock_pdf.pages = [mock_page]

    with patch("pdfplumber.open") as mock_open:
        mock_open.return_value.__enter__.return_value = mock_pdf
        result = extract_text("/fake/path.pdf")

    assert result[0]["text"] == "KV cache reduces latency"
    assert not re.search(r"[a-z][A-Z]", result[0]["text"])


def test_extract_text_real_pdf(tmp_path: Path) -> None:
    """Round-trip test using a real PDF generated by fpdf2.

    Verifies that extract_text() returns properly spaced words (no merged tokens)
    and correct page numbers — the regression that motivated this fix.
    """
    pytest.importorskip("fpdf")
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    pdf.cell(text="KV cache reduces inference latency significantly.")
    pdf.ln()
    pdf.cell(text="Retrieval augmented generation improves accuracy.")

    pdf.add_page()
    pdf.cell(text="Second page content here.")

    pdf_path = tmp_path / "test.pdf"
    pdf.output(str(pdf_path))

    result = extract_text(str(pdf_path))

    assert len(result) == 2
    assert result[0]["page"] == 1
    assert result[1]["page"] == 2

    page1_text = result[0]["text"]
    assert not re.search(r"[a-z][A-Z]", page1_text), f"merged words in: {page1_text!r}"
    assert "KV" in page1_text
    assert "cache" in page1_text
