"""Generate a static portfolio page from the paper API."""

import argparse
import html
import json
import sys
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen


def fetch_all(url: str) -> list:
    """Fetch all items from a paginated list endpoint."""
    items = []
    limit = 100
    offset = 0
    while True:
        try:
            resp = urlopen(f"{url}&limit={limit}&offset={offset}", timeout=15)
            data = json.loads(resp.read())
        except URLError as e:
            print(f"[warn] fetch failed: {e}", file=sys.stderr)
            break
        batch = data.get("papers") or data.get("summaries") or []
        items.extend(batch)
        if len(batch) < limit:
            break
        offset += limit
    return items


def score_badge(score) -> str:
    if score is None:
        return '<span class="text-xs text-gray-400">—</span>'
    pct = int(score * 100)
    if score >= 0.7:
        color = "bg-green-100 text-green-800"
    elif score >= 0.4:
        color = "bg-yellow-100 text-yellow-800"
    else:
        color = "bg-gray-100 text-gray-500"
    return f'<span class="inline-block text-xs px-2 py-0.5 rounded-full font-mono {color}">{pct}</span>'


def source_link(paper: dict) -> str:
    source = paper.get("source") or ""
    title = html.escape(paper.get("title") or paper.get("file_name", "Untitled"))
    if source == "arxiv":
        fname = paper.get("file_name", "")
        arxiv_id = fname.replace(".pdf", "").replace("_", "/") if fname else ""
        if arxiv_id:
            return f'<a href="https://arxiv.org/abs/{arxiv_id}" target="_blank" rel="noopener" class="hover:underline text-blue-700">{title}</a>'
    return f"<span>{title}</span>"


def category_badges(cats) -> str:
    if not cats:
        return ""
    badges = "".join(
        f'<span class="inline-block text-xs px-1.5 py-0.5 rounded bg-blue-50 text-blue-700 font-mono">{html.escape(c)}</span>'
        for c in cats[:5]
    )
    return f'<div class="flex flex-wrap gap-1 mt-1">{badges}</div>'


def build_html(papers: list, summaries_by_id: dict, updated: str) -> str:
    cards = []
    for p in papers:
        pid = p.get("id")
        authors = p.get("authors") or []
        authors_str = html.escape(", ".join(authors[:4]))
        if len(authors) > 4:
            authors_str += " et al."
        pub_date = (p.get("published_date") or "")[:10]
        source_label = html.escape((p.get("source") or "").upper())
        summ = summaries_by_id.get(pid, {})
        objective = html.escape(summ.get("objective") or "")

        card = f"""
    <article class="bg-white rounded-xl border border-gray-100 shadow-sm p-5 space-y-2">
      <div class="flex items-start justify-between gap-3">
        <h2 class="text-sm font-semibold text-gray-900 leading-snug flex-1">{source_link(p)}</h2>
        {score_badge(p.get("score"))}
      </div>
      {f'<p class="text-xs text-gray-500">{authors_str}</p>' if authors_str else ""}
      <div class="flex items-center gap-2 text-xs text-gray-400">
        {f"<span>{pub_date}</span>" if pub_date else ""}
        {f'<span class="uppercase tracking-wide font-medium text-gray-300">{source_label}</span>' if source_label else ""}
      </div>
      {category_badges(p.get("categories"))}
      {f'<p class="text-xs text-gray-600 mt-2 line-clamp-3">{objective}</p>' if objective else ""}
    </article>"""
        cards.append(card)

    cards_html = "\n".join(cards)
    count = len(papers)

    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Papers — @flipslidersand</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    .line-clamp-3 {{ display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }}
  </style>
</head>
<body class="bg-gray-50 min-h-screen font-sans text-gray-800">
  <header class="bg-white border-b border-gray-100 px-6 py-5">
    <div class="max-w-3xl mx-auto">
      <h1 class="text-xl font-bold tracking-tight">Reading List</h1>
      <p class="text-sm text-gray-500 mt-1">
        <a href="https://github.com/flipslidersand" class="hover:underline text-blue-600">@flipslidersand</a>
        &mdash; {count} papers &mdash; updated {updated}
      </p>
      <p class="text-xs text-gray-400 mt-2">Score = freshness + category relevance (0–100). Sorted by score.</p>
    </div>
  </header>
  <main class="max-w-3xl mx-auto py-8 px-4 space-y-4">
    {cards_html}
  </main>
  <footer class="text-center text-xs text-gray-300 py-8">
    Generated by <a href="https://github.com/flipslidersand/academic-paper-system" class="hover:underline">academic-paper-system</a>
  </footer>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser(description="Generate portfolio static site")
    parser.add_argument("--api-url", default="http://localhost:8020")
    parser.add_argument("--output-dir", default="docs")
    args = parser.parse_args()

    api = args.api_url.rstrip("/")
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    print("Fetching papers ...", file=sys.stderr)
    papers = fetch_all(f"{api}/papers?sort=score")
    print(f"  {len(papers)} papers", file=sys.stderr)

    print("Fetching summaries ...", file=sys.stderr)
    summaries = fetch_all(f"{api}/summaries?")
    summaries_by_id = {s["paper_id"]: s for s in summaries}
    print(f"  {len(summaries)} summaries", file=sys.stderr)

    from datetime import date

    updated = date.today().isoformat()

    html_content = build_html(papers, summaries_by_id, updated)
    (out / "index.html").write_text(html_content, encoding="utf-8")
    print(f"Wrote {out}/index.html", file=sys.stderr)

    json_content = json.dumps(
        {"updated": updated, "count": len(papers), "papers": papers},
        ensure_ascii=False,
        indent=2,
    )
    (out / "papers.json").write_text(json_content, encoding="utf-8")
    print(f"Wrote {out}/papers.json", file=sys.stderr)


if __name__ == "__main__":
    main()
